# Generated by Django 5.2.17 on 2026-08-28 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客戶名稱')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '客戶',
                'verbose_name_plural': '客戶',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話')),
                ('position', models.CharField(default='清潔人員', max_length=50, verbose_name='職位')),
                ('available', models.BooleanField(default=True, verbose_name='可派遣')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=30, unique=True, verbose_name='車號')),
                ('name', models.CharField(max_length=100, verbose_name='車輛名稱')),
                ('vehicle_type', models.CharField(blank=True, max_length=50, verbose_name='車型')),
                ('status', models.CharField(choices=[('可用', '可用'), ('維修中', '維修中'), ('停用', '停用')], default='可用', max_length=20, verbose_name='狀態')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=50, unique=True, verbose_name='案件編號')),
                ('clean_date', models.DateField(verbose_name='清潔日期')),
                ('clean_time', models.TimeField(verbose_name='清潔時間')),
                ('address', models.CharField(max_length=255, verbose_name='清潔地址')),
                ('clean_type', models.CharField(default='一般清潔', max_length=100, verbose_name='清潔類型')),
                ('status', models.CharField(choices=[('待處理', '待處理'), ('已派車', '已派車'), ('進行中', '進行中'), ('已完成', '已完成'), ('取消', '取消')], default='待處理', max_length=20, verbose_name='狀態')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dispatch.customer', verbose_name='客戶')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='出發時間')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='返回時間')),
                ('status', models.CharField(choices=[('已排程', '已排程'), ('出發', '出發'), ('完成', '完成'), ('取消', '取消')], default='已排程', max_length=20, verbose_name='派車狀態')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('cleaner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaner_dispatches', to='dispatch.employee', verbose_name='清潔人員')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_dispatches', to='dispatch.employee', verbose_name='司機')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dispatch.job', verbose_name='案件')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.vehicle', verbose_name='車輛')),
            ],
        ),
    ]
